#Start with a base image containing Java runtime
FROM openjdk:11-slim

# Add Maintainer Info
LABEL maintainer="Vaibhav Saxena <reachvaibhavsaxena@gmail.com>"

# The application's jar file [Defined as a variable in pom.xml Docker plugin]
ARG JAR_FILE

# Add the application's jar to the container
COPY ${JAR_FILE} app.jar

#execute the application
ENTRYPOINT ["java","-jar","/app.jar"]